name: Jfrog integrate with GitHub actions
on:
  workflow_dispatch

env:
  aws-region: ap-southeast-1

jobs:
  Jfrog-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: configure Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          
          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
       
      - name: AWS CLI configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}
      
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
      
      - name: Run JFrog Scan
        id: jfrog-scan
        run: |
          jf audit --watches "demo" 
      
      # - name: Check JFrog Scan Results
      #   run: |
      #     if grep -qE "Found [1-9][0-9]* IaC vulnerabilities" <<< "${{ steps.jfrog-scan.outputs.stdout }}"; then
      #       echo "Found IaC vulnerabilities. Stopping Terraform plan."
      #       exit 1
      #     else
      #       echo "No non-zero IaC vulnerabilities found. Proceeding with Terraform plan."
      #     fi

      - name: Plan Terraform
        if: failure()
        run: terraform plan 

